version: "3"

services:
  base: &base
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    image: app/development

  rails:
    <<: *base
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - REDIS_PERSISTENCE_URL=redis://redis:6379
      - RAILS_ENV=development
      - BINDING=0.0.0.0
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - cache:/app/tmp/cache
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    command: ./bin/rails server

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  redis:
  node_modules:
  cache:
