name: drun Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    name: Test with Docker
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version

    - name: Set environment variable to force Docker
      run: |
        echo "FORCE_DOCKER=1" >> $GITHUB_ENV

    - name: Run drun tests with Docker
      run: |
        chmod +x ./tests/engine-test.sh
        ./tests/engine-test.sh

  test-podman:
    name: Test with Podman
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version

    - name: Install podman-compose
      run: |
        sudo pip install podman-compose
        podman-compose --version

    - name: Set environment variable to force Podman
      run: |
        echo "FORCE_DOCKER=" >> $GITHUB_ENV

    - name: Run drun tests with Podman
      run: |
        chmod +x ./tests/engine-test.sh
        ./tests/engine-test.sh
